### ISSUE TITLE
Question: How to pattern match/branch code?

### ISSUE THREAD

**Issue by dougflip** [fnl/pymonad#1]
Sorry to ask this in a fork, but I couldn't find a way to ask in bitbucket!

I am wondering how I would "branch" my code at the end of a chain of function calls. For example, if I `fmap` over an `Either` I'll end up with a `Left` or a `Right` and most likely want to perform a different action based on that result. What is the preferred way to handle that with this lib? Hoping someone here can help, thanks!

**Comment by fnl** [comment]
https://github.com/fnl/pymonad/blob/master/pymonad/test/test_Either.py

Does that clarify how Either is used?

**Comment by dougflip** [comment]
Ya, that helps! It looks like generally two Either instances are equal if their contents are also equal. How about just a generic "Is this value a Left or Right" function though? Without needing to know the exact contents until later? Basically, I want to run a series of calls and then at the end know if I ended up with a Right or Left without needing to also compare the contents. Does that make sense?

Thanks for pointing me at the tests! I am going to read through more of them 👍

**Comment by fnl** [comment]
Problem is that Python has no typed λ calculus, and you don’t get nice semantics for doing elegant pattern matching to ensure you are correctly plugging things together via generalized algebraic data types, such as case classes in Scala. But hey, if you _really_ want to be doing FP, you probably anyway should be looking into a “proper” language for that (like ML, Haskell, Scala, F#, LISP, Scheme, Clojure, asf.). That said, you always can do “if isinstance(myEither, Left)" for example - not quite a elegant as matching with GADTs, but at least it gets you what you want. More general, as a word of warning, this library is fun for fooling around with FP concepts, but I am pretty sure I wouldn’t do anything serious with it…

**Comment by dougflip** [comment]
Makes total sense! I've seen other libs define a method that takes 2 callbacks for things like Maybe and Either ([Daggy's cata as an example](https://github.com/fantasyland/daggy)) so I may try to play around with adding something like that.

In any case, thanks so much for the help - I'll close out this issue.
